// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Y2Mq_6A_xX7fMfQzCkx3zpKeY3V6FzA',
    appId: '1:608310682636:web:05d27168d79fbf1c0dba29',
    messagingSenderId: '608310682636',
    projectId: 'flash-chat-493fb',
    authDomain: 'flash-chat-493fb.firebaseapp.com',
    storageBucket: 'flash-chat-493fb.appspot.com',
    measurementId: 'G-2NZ3Q7XWQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAse684E0CcIQHzs1gVYAI4bKZgVTrNKk',
    appId: '1:608310682636:android:a07c2e64a250711b0dba29',
    messagingSenderId: '608310682636',
    projectId: 'flash-chat-493fb',
    storageBucket: 'flash-chat-493fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHibVIQpm8WxzVAfDzTn6feSczYfsRcxA',
    appId: '1:608310682636:ios:94d0a9e7249435c60dba29',
    messagingSenderId: '608310682636',
    projectId: 'flash-chat-493fb',
    storageBucket: 'flash-chat-493fb.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHibVIQpm8WxzVAfDzTn6feSczYfsRcxA',
    appId: '1:608310682636:ios:94d0a9e7249435c60dba29',
    messagingSenderId: '608310682636',
    projectId: 'flash-chat-493fb',
    storageBucket: 'flash-chat-493fb.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9Y2Mq_6A_xX7fMfQzCkx3zpKeY3V6FzA',
    appId: '1:608310682636:web:f811cae486077ce80dba29',
    messagingSenderId: '608310682636',
    projectId: 'flash-chat-493fb',
    authDomain: 'flash-chat-493fb.firebaseapp.com',
    storageBucket: 'flash-chat-493fb.appspot.com',
    measurementId: 'G-SFJ6D6PDQC',
  );

}